### ISSUE TITLE
Iš kur atsiranda dulkės?

### ISSUE THREAD

**Issue by Ernbaku** [PI17D/VygandasEidukis#11]

**Comment by ErnestasBakucionis** [comment]
Daugeliui šis klausimas gali pasirodyti tolygus ne ką mažiau svarbiam klausimui: Kur dingsta pinigai? O tarp kitko, yra žinoma, kad dulkės kaupiasi net ir butuose, kuriuose niekas negyvena. Įvairių eksperimentų metu įrodyta, kad net ir užrakintame bute su sandariai uždarytais langais per dvi savaites ant grindų bei horizontalių baldų paviršių viename kvadratiniame centimetre prisikaupė net apie 12 tūkstančių dulkių dalelių. Tyrimai rodo, kad 35 proc. jų sudarė mineralų dalelės, 12 proc. – tekstilės ir popieriaus pluošto, 19 proc. – odos žvyneliai, 7 proc. – žiedadulkės, 3 proc. - suodžių ir dūmų dalelės. Dar  24 proc. dalelių kilmė nebuvo nustatyta. Šie duomenys rodo, kad  dulkės, esančios ore, labai lėtai nusėda  ir net sandariai užrakinti langai bei durys  joms nėra neįveikiama kliūtis.

**Comment by antibiotikas** [comment]
tavo mama

**Comment by SarunasBrazdzionis** [comment]
# _**Dievas yra**_

**Comment by antibiotikas** [comment]
# Žemė plokščia buvo iki 14xx

**Comment by deadlyhacker777** [comment]
....

**Comment by SarunasBrazdzionis** [comment]
@antibiotikas Nebesvaik

**Comment by ErnestasBakucionis** [comment]
Daugeliui šis klausimas gali pasirodyti tolygus ne ką mažiau svarbiam klausimui: Kur dingsta pinigai? O tarp kitko, yra žinoma, kad dulkės kaupiasi net ir butuose, kuriuose niekas negyvena. Įvairių eksperimentų metu įrodyta, kad net ir užrakintame bute su sandariai uždarytais langais per dvi savaites ant grindų bei horizontalių baldų paviršių viename kvadratiniame centimetre prisikaupė net apie 12 tūkstančių dulkių dalelių. Tyrimai rodo, kad 35 proc. jų sudarė mineralų dalelės, 12 proc. – tekstilės ir popieriaus pluošto, 19 proc. – odos žvyneliai, 7 proc. – žiedadulkės, 3 proc. - suodžių ir dūmų dalelės. Dar  24 proc. dalelių kilmė nebuvo nustatyta. Šie duomenys rodo, kad  dulkės, esančios ore, labai lėtai nusėda  ir net sandariai užrakinti langai bei durys  joms nėra neįveikiama kliūtis.

**Comment by Ernbaku** [comment]
### 

> _Daugeliui šis klausimas gali pasirodyti tolygus ne ką mažiau svarbiam klausimui: Kur dingsta pinigai? O tarp kitko, yra žinoma, kad dulkės kaupiasi net ir butuose, kuriuose niekas negyvena. Įvairių eksperimentų metu įrodyta, kad net ir užrakintame bute su sandariai uždarytais langais per dvi savaites ant grindų bei horizontalių baldų paviršių viename kvadratiniame centimetre prisikaupė net apie 12 tūkstančių dulkių dalelių. Tyrimai rodo, kad 35 proc. jų sudarė mineralų dalelės, 12 proc. – tekstilės ir popieriaus pluošto, 19 proc. – odos žvyneliai, 7 proc. – žiedadulkės, 3 proc. - suodžių ir dūmų dalelės. Dar  24 proc. dalelių kilmė nebuvo nustatyta. Šie duomenys rodo, kad  dulkės, esančios ore, labai lėtai nusėda  ir net sandariai užrakinti langai bei durys  joms nėra neįveikiama kliūtis.__

**Comment by AugustasKaznavicius** [comment]
sw all
